// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// AUTO-GENERATED by scripts/gen_replay.mjs from paper_opps.jsonl — do not edit.
// Replays every unique paper-mode opportunity (best-net record per route) on a
// Base fork at the exact block it was claimed, through the real swap path, and
// reports realized vs predicted profit. Hop kinds are factory()-classified.

import {Test, console2} from "forge-std/Test.sol";
import {ArbExecutor, IERC20} from "../src/ArbExecutor.sol";

interface IPoolTokens {
    function token0() external view returns (address);
    function token1() external view returns (address);
}

/// ArbExecutor minus the profit guard: measure realized output of a route.
contract ReplayHarness is ArbExecutor {
    function run(ArbExecutor.Hop[] calldata hops, uint256 amountIn) external returns (uint256) {
        _runHops(hops, new ArbExecutor.V4Key[](0), amountIn);
        return IERC20(WETH).balanceOf(address(this));
    }

    function runV4(ArbExecutor.Hop[] calldata hops, ArbExecutor.V4Key[] calldata v4Keys, uint256 amountIn)
        external
        returns (uint256)
    {
        _runHops(hops, v4Keys, amountIn);
        return IERC20(WETH).balanceOf(address(this));
    }
}

contract ReplayAllTest is Test {

    function testReplayBatch00() public {

        {
            address[] memory p = new address[](2);
            uint8[] memory k = new uint8[](2);
            uint16[] memory f = new uint16[](2);
            p[0] = address(uint160(0x0066660fbcd3829932586a5af62093ee75faa91f9f)); k[0] = 2; f[0] = 0;
            p[1] = address(uint160(0x003f0296bf652e19bca772ec3df08b32732f93014a)); k[1] = 2; f[1] = 0;
            _replay("r001_id11954_blk48830908", 48830908, 24185548105404392, 3183372598251, 3653495094108, p, k, f);
        }
    }

    /// Logs, per record: "RES <name>" then realized NET profit (gross minus the
    /// bot's gas_cost_wei estimate) and the bot's own predicted net — both as
    /// bare int lines for easy machine parsing. "RES <name> REVERTED" on revert.
    function _replay(
        string memory name,
        uint256 blockNo,
        uint256 amountIn,
        uint256 gasCost,
        uint256 predictedNet,
        address[] memory pools,
        uint8[] memory kinds,
        uint16[] memory fees
    ) internal {
        vm.createSelectFork(vm.envString("BASE_RPC_URL"), blockNo);
        ReplayHarness h = new ReplayHarness();
        address weth = h.WETH();
        deal(weth, address(h), amountIn);

        ArbExecutor.Hop[] memory hops = new ArbExecutor.Hop[](pools.length);
        address tokenIn = weth;
        for (uint256 i = 0; i < pools.length; i++) {
            address t0 = IPoolTokens(pools[i]).token0();
            bool zeroForOne = tokenIn == t0;
            hops[i] = ArbExecutor.Hop({kind: kinds[i], pool: pools[i], zeroForOne: zeroForOne, feeBps: fees[i]});
            tokenIn = zeroForOne ? IPoolTokens(pools[i]).token1() : t0;
        }
        require(tokenIn == weth, "route does not cycle back to WETH");

        try h.run(hops, amountIn) returns (uint256 out) {
            int256 realizedNet = int256(out) - int256(amountIn) - int256(gasCost);
            console2.log(string.concat("RES ", name));
            console2.logInt(realizedNet);
            console2.logInt(int256(predictedNet));
        } catch {
            console2.log(string.concat("RES ", name, " REVERTED"));
        }
    }

    /// V4-aware variant: directions come from the record (V4 pools have no
    /// address to probe token0() on), and the V4Key array is passed through.
    function _replayV4(
        string memory name,
        uint256 blockNo,
        uint256 amountIn,
        uint256 gasCost,
        uint256 predictedNet,
        address[] memory pools,
        uint8[] memory kinds,
        uint16[] memory fees,
        ArbExecutor.V4Key[] memory v4Keys,
        bool[] memory zfo
    ) internal {
        vm.createSelectFork(vm.envString("BASE_RPC_URL"), blockNo);
        ReplayHarness h = new ReplayHarness();
        deal(h.WETH(), address(h), amountIn);

        ArbExecutor.Hop[] memory hops = new ArbExecutor.Hop[](pools.length);
        for (uint256 i = 0; i < pools.length; i++) {
            hops[i] = ArbExecutor.Hop({kind: kinds[i], pool: pools[i], zeroForOne: zfo[i], feeBps: fees[i]});
        }

        try h.runV4(hops, v4Keys, amountIn) returns (uint256 out) {
            int256 realizedNet = int256(out) - int256(amountIn) - int256(gasCost);
            console2.log(string.concat("RES ", name));
            console2.logInt(realizedNet);
            console2.logInt(int256(predictedNet));
        } catch {
            console2.log(string.concat("RES ", name, " REVERTED"));
        }
    }
}
